namespace GModMount.Source;

/// <summary>
/// Constants used across Source Engine file formats.
/// </summary>
public static class SourceConstants
{
	// MDL Magic and Versions
	public const int MDL_ID = 0x54534449; // "IDST"
	public const int MDL_VERSION_44 = 44;
	public const int MDL_VERSION_45 = 45;
	public const int MDL_VERSION_46 = 46;
	public const int MDL_VERSION_47 = 47;
	public const int MDL_VERSION_48 = 48;
	public const int MDL_VERSION_49 = 49;
	public const int MDL_VERSION_53 = 53;

	// VVD Magic and Versions
	public const int VVD_ID = 0x56534449; // "IDSV"
	public const int VVD_VERSION = 4;

	// VTX Magic and Versions
	public const int VTX_VERSION = 7;

	// Max bone influences per vertex
	public const int MAX_BONES_PER_VERTEX = 3;

	// Max LODs
	public const int MAX_LOD_COUNT = 8;

	// Studio flags
	public const int STUDIOHDR_FLAGS_AUTOGENERATED_HITBOX = 0x00000001;
	public const int STUDIOHDR_FLAGS_USES_ENV_CUBEMAP = 0x00000002;
	public const int STUDIOHDR_FLAGS_FORCE_OPAQUE = 0x00000004;
	public const int STUDIOHDR_FLAGS_TRANSLUCENT_TWOPASS = 0x00000008;
	public const int STUDIOHDR_FLAGS_STATIC_PROP = 0x00000010;
	public const int STUDIOHDR_FLAGS_USES_FB_TEXTURE = 0x00000020;
	public const int STUDIOHDR_FLAGS_HASSHADOWLOD = 0x00000040;
	public const int STUDIOHDR_FLAGS_USES_BUMPMAPPING = 0x00000080;

	// Bone flags
	public const int BONE_PHYSICALLY_SIMULATED = 0x00000001;
	public const int BONE_PHYSICS_PROCEDURAL = 0x00000002;
	public const int BONE_ALWAYS_PROCEDURAL = 0x00000004;
	public const int BONE_SCREEN_ALIGN_SPHERE = 0x00000008;
	public const int BONE_SCREEN_ALIGN_CYLINDER = 0x00000010;
	public const int BONE_USED_BY_VERTEX_LOD0 = 0x00000400;
	public const int BONE_USED_BY_VERTEX_LOD1 = 0x00000800;
	public const int BONE_USED_BY_VERTEX_LOD2 = 0x00001000;
	public const int BONE_USED_BY_VERTEX_LOD3 = 0x00002000;
	public const int BONE_USED_BY_VERTEX_LOD4 = 0x00004000;
	public const int BONE_USED_BY_VERTEX_LOD5 = 0x00008000;
	public const int BONE_USED_BY_VERTEX_LOD6 = 0x00010000;
	public const int BONE_USED_BY_VERTEX_LOD7 = 0x00020000;

	// Strip group flags
	public const byte STRIP_IS_TRILIST = 0x01;
	public const byte STRIP_IS_TRISTRIP = 0x02;

	// Strip flags
	public const byte STRIPGROUP_IS_FLEXED = 0x01;
	public const byte STRIPGROUP_IS_HWSKINNED = 0x02;
	public const byte STRIPGROUP_IS_DELTA_FLEXED = 0x04;
	public const byte STRIPGROUP_SUPPRESS_HW_MORPH = 0x08;

	/// <summary>
	/// Scale factor from Source units to s&box units (Source uses inches, roughly)
	/// </summary>
	public const float SCALE = 1.0f; // Adjust as needed for s&box
}
